// generated by cap, DO NOT EDIT.
package handle

import (
	"fmt"

	"framework/pkg/cap/msg/i18n"
	"golang.org/x/text/language"
)

// supported languages:
var (
	Lang_zhCN       = language.Make("zh-CN")
	languageMatcher = language.NewMatcher([]language.Tag{Lang_zhCN})
)

// language matcher
func MatchLang(lang string) (tag language.Tag, err error) {
	langTag := language.Make(lang)
	matchedTag, _, c := languageMatcher.Match(langTag)
	if c < language.High {
		return matchedTag, fmt.Errorf("no confidence language matched")
	}
	return matchedTag, nil
}

// language id definitions:
// ERR_UNKNOWN 未知错误[%s]
const ERR_UNKNOWN = i18n.TrID("v_handle_ERR_UNKNOWN")
