// generated by cap at 2020-02-05 16:31:01.1209477 +0800 CST m=+0.007001001, DO NOT EDIT.
package handle

import (
	"fmt"

	"github.com/hoorayui/core-framework/pkg/cap/msg/i18n"
	"golang.org/x/text/language"
)

var handle_lr handle_langRegistry

func initTrRegistry() {
	if handle_lr == nil {
		handle_lr = handle_langRegistry{}
	}
}

func (l handle_langRegistry) addTranslation(id i18n.TrID, lang language.Tag, translation string) error {
	if ts, ok := handle_lr[id]; ok {
		if _, ok := ts[lang]; ok {
			return fmt.Errorf("dupplicate translation for [%s#%s]", id, lang.String())
		}
		l[id][lang] = translation
	} else {
		l[id] = map[language.Tag]string{
			lang: translation,
		}
	}
	return nil
}

func init() {
	i18n.AddTrCandidates(&handle_tr{})
}

// map[langID]map[langCode]translation
type handle_langRegistry map[i18n.TrID]map[language.Tag]string

type handle_tr struct{}

func (t *handle_tr) Translate(lang language.Tag, id i18n.TrID, args ...interface{}) (string, error) {
	if ts, ok := handle_lr[id]; ok {
		if t, ok := ts[lang]; ok {
			return fmt.Sprintf(t, args...), nil
		}
	}
	return "", i18n.ErrNoTranslateCandidate
}
