// generated by cap from unknown.toml at 2020-02-05 16:31:01.1229475 +0800 CST m=+0.009000801, DO NOT EDIT.
package handle

import "golang.org/x/text/language"

func init() {
	initTrRegistry()
	handle_lr.addTranslation(ERR_UNKNOWN, language.Make("zh-CN"), "未知错误[%s]")
}
