// generated by cap, DO NOT EDIT.
package test

import (
	"fmt"

	"github.com/hoorayui/core-framework/pkg/cap/msg/i18n"
	"golang.org/x/text/language"
)

// supported languages:
var (
	LangZhcn        = language.Make("zh-CN")
	LangEnus        = language.Make("en-US")
	languageMatcher = language.NewMatcher([]language.Tag{LangZhcn, LangEnus})
)

// language matcher
func MatchLang(lang string) (tag language.Tag, err error) {
	langTag := language.Make(lang)
	matchedTag, _, c := languageMatcher.Match(langTag)
	if c < language.High {
		return matchedTag, fmt.Errorf("no confidence language matched")
	}
	return matchedTag, nil
}

// language id definition:
// Err1 用户名或密码错误
const Err1 = i18n.TrID("v_ERR_1")

// ERR_2 测试
const ERR_2 = i18n.TrID("v_ERR_2")
