// generated by cap from user_error.toml at 2019-12-18 19:24:24.4584476 +0800 CST m=+0.015716101, DO NOT EDIT.
package test

import "golang.org/x/text/language"

func init() {
	initTrRegistry()
	test_lr.addTranslation(Err1, language.Make("zh-CN"), "用户名或密码错误")
	test_lr.addTranslation(Err1, language.Make("en-US"), "invalid username or password")
	test_lr.addTranslation(ERR_2, language.Make("zh-CN"), "测试")
	test_lr.addTranslation(ERR_2, language.Make("en-US"), "test")
}
