# template
[ErrOperatePermissionDenied]
zh-CN = "没有权限操作其他人创建的模板"
[ErrDisableSharingFormToAllUsers]
zh-CN = "禁止向所有用户共享表单"

# service
[ErrNotFormAction] 
zh-CN = "该操作(%s)不是一个合法的表单操作"
[ErrTempTableNotSupportTemplateOp] 
zh-CN = "临时表单不支持模板操作"

# registry
[ErrDupplicateNodeID]
zh-CN = "重复节点ID(%s)"
[ErrNodeNotExist] 
zh-CN = "节点ID(%s)不存在"
[ErrInvalidColumnID] 
zh-CN = "无效的列ID(%s)"
[ErrOptionNotFound]
zh-CN = "无法查询到(%d):(%s)"
[ErrOperatorNotSupported]
zh-CN = "操作符(%s)在该列(%s.%s)不被支持"
[ErrInvalidConditionValue]
zh-CN = "无效的条件右值数量, 应该输入 (%s) 个参数, 实际输入了 (%d) 个参数"
[ErrInvalidConditionValueType]
zh-CN = "无效的列(%s)右值类型, want (%s), got (%s)"
[ErrAggregateNotSupported]
zh-CN = "该列(%s.%s)不支持聚合"
[ErrTplNullOutput]
zh-CN = "模板输出列为空"
[ErrInvalidRowActionID]
zh-CN = "无效的操作ID(%s)"
[ErrIllegalArguments]
zh-CN = "非法参数(%s)"
[ErrDupplicateColumnID]
zh-CN = "重复列ID(%s)"

# mysql

[ErrRowsAffectedZero] 
zh-CN = "数据没有变化"
[ErrDuplicateEntry]
zh-CN = "已存在重复记录"
[ErrDataTooLong] 
zh-CN = "输入的数据超过最大长度[%s]"

# dbdriver
[ErrInvalidValueForCondition]
zh-CN = "无效的条件参数(%s)"
[ErrUnknownOperator] 
zh-CN = "未知的操作符(%s)"
[ErrOperatorNotSupportedForColumn]
zh-CN = "操作符(%s)在该列(%s)不被支持"
[ErrResultExceedMaxLimit]
zh-CN = "查询结果数量[%d]超出单次最大数量[%d]限制，请分次查询"


# utils
[ErrFailedMapValue]
zh-CN = "转换数据(%v): dt(%s) => vt(%s) 失败"
[ErrFailedParseConditionValue]
zh-CN = "解析条件右值失败(%s): %v"

# data
[ErrDriverNotFoundForTable] 
zh-CN = "无法找到表(%s)的数据驱动"
[ErrInvalidColumnFromStruct] 
zh-CN = "invalid column(%s) from struct(%v)"
[ErrNotResultForID] 
zh-CN = "无法查询到ID(%s)对应的数据"
