// Code generated by cap from [table.toml] at [2023-02-22 18:17:36.5656116 +0800 CST m=+0.079153801], DO NOT EDIT.
package errors

import language "golang.org/x/text/language"

func init() {
	initTrRegistry()
	errors_lr.addTranslation(ErrDisableSharingFormToAllUsers, language.Make("zh-CN"), "禁止向所有用户共享表单")
	errors_lr.addTranslation(ErrIllegalArguments, language.Make("zh-CN"), "非法参数(%s)")
	errors_lr.addTranslation(ErrDupplicateNodeID, language.Make("zh-CN"), "重复节点ID(%s)")
	errors_lr.addTranslation(ErrUnknownOperator, language.Make("zh-CN"), "未知的操作符(%s)")
	errors_lr.addTranslation(ErrFailedMapValue, language.Make("zh-CN"), "转换数据(%v): dt(%s) => vt(%s) 失败")
	errors_lr.addTranslation(ErrNotResultForID, language.Make("zh-CN"), "无法查询到ID(%s)对应的数据")
	errors_lr.addTranslation(ErrNotFormAction, language.Make("zh-CN"), "该操作(%s)不是一个合法的表单操作")
	errors_lr.addTranslation(ErrOperatorNotSupported, language.Make("zh-CN"), "操作符(%s)在该列(%s.%s)不被支持")
	errors_lr.addTranslation(ErrOptionNotFound, language.Make("zh-CN"), "无法查询到(%d):(%s)")
	errors_lr.addTranslation(ErrResultExceedMaxLimit, language.Make("zh-CN"), "查询结果数量[%d]超出单次最大数量[%d]限制，请分次查询")
	errors_lr.addTranslation(ErrTempTableNotSupportTemplateOp, language.Make("zh-CN"), "临时表单不支持模板操作")
	errors_lr.addTranslation(ErrInvalidConditionValueType, language.Make("zh-CN"), "无效的列(%s)右值类型, want (%s), got (%s)")
	errors_lr.addTranslation(ErrOperatePermissionDenied, language.Make("zh-CN"), "没有权限操作其他人创建的模板")
	errors_lr.addTranslation(ErrTplNullOutput, language.Make("zh-CN"), "模板输出列为空")
	errors_lr.addTranslation(ErrDataTooLong, language.Make("zh-CN"), "输入的数据超过最大长度[%s]")
	errors_lr.addTranslation(ErrNodeNotExist, language.Make("zh-CN"), "节点ID(%s)不存在")
	errors_lr.addTranslation(ErrInvalidColumnFromStruct, language.Make("zh-CN"), "invalid column(%s) from struct(%v)")
	errors_lr.addTranslation(ErrDuplicateEntry, language.Make("zh-CN"), "已存在重复记录")
	errors_lr.addTranslation(ErrOperatorNotSupportedForColumn, language.Make("zh-CN"), "操作符(%s)在该列(%s)不被支持")
	errors_lr.addTranslation(ErrInvalidRowActionID, language.Make("zh-CN"), "无效的操作ID(%s)")
	errors_lr.addTranslation(ErrRowsAffectedZero, language.Make("zh-CN"), "数据没有变化")
	errors_lr.addTranslation(ErrInvalidColumnID, language.Make("zh-CN"), "无效的列ID(%s)")
	errors_lr.addTranslation(ErrAggregateNotSupported, language.Make("zh-CN"), "该列(%s.%s)不支持聚合")
	errors_lr.addTranslation(ErrDriverNotFoundForTable, language.Make("zh-CN"), "无法找到表(%s)的数据驱动")
	errors_lr.addTranslation(ErrDupplicateColumnID, language.Make("zh-CN"), "重复列ID(%s)")
	errors_lr.addTranslation(ErrInvalidConditionValue, language.Make("zh-CN"), "无效的条件右值数量, 应该输入 (%s) 个参数, 实际输入了 (%d) 个参数")
	errors_lr.addTranslation(ErrFailedParseConditionValue, language.Make("zh-CN"), "解析条件右值失败(%s): %v")
	errors_lr.addTranslation(ErrInvalidValueForCondition, language.Make("zh-CN"), "无效的条件参数(%s)")
}
