--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.338.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 5/5/2022 6:24:14 PM
-- Server version: 8.0.21
-- Client version: 4.1
--
-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */
;
-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */
;
-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';
--
-- Set default database
--
USE tabletest;
--
-- Drop table `testtable`
--
DROP TABLE IF EXISTS testtable;
--
-- Drop table `table_template_share`
--
DROP TABLE IF EXISTS table_template_share;
--
-- Drop table `table_template`
--
DROP TABLE IF EXISTS table_template;
--
-- Set default database
--
USE tabletest;
--
-- Create table `table_template`
--
CREATE TABLE table_template (
    id varchar(64) NOT NULL DEFAULT '',
    name varchar(128) NOT NULL DEFAULT '' COMMENT '模板名，table_id+模板名需唯一',
    table_id varchar(64) NOT NULL DEFAULT '',
    f_access tinyint NOT NULL,
    f_create_user int NOT NULL,
    f_create_time timestamp NULL DEFAULT NULL,
    f_mod_time timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    body blob DEFAULT NULL,
    PRIMARY KEY (id)
) ENGINE = INNODB,
AVG_ROW_LENGTH = 780,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;
--
-- Create table `table_template_share`
--
CREATE TABLE table_template_share (
    template_id varchar(64) NOT NULL DEFAULT '' COMMENT '模板id',
    user_id int NOT NULL COMMENT '用户id',
    PRIMARY KEY (template_id, user_id)
) ENGINE = INNODB,
AVG_ROW_LENGTH = 910,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = '报表模板共享信息';
--
-- Create foreign key
--
ALTER TABLE table_template_share
ADD CONSTRAINT FK_table_template_share_template_id FOREIGN KEY (template_id) REFERENCES mts2.table_template (id) ON DELETE CASCADE ON UPDATE CASCADE;
--
-- Create table `testtable`
--
CREATE TABLE tabletest.testtable (
    f1 int NOT NULL AUTO_INCREMENT COMMENT '字段1|',
    f2 varchar(64) DEFAULT NULL COMMENT '字段2|',
    f3 datetime DEFAULT NULL COMMENT '字段3|',
    f4 tinyint DEFAULT NULL COMMENT '字段4|',
    f5 varchar(64) DEFAULT NULL COMMENT '字段5|',
    f6 varchar(64) DEFAULT NULL COMMENT '字段6|',
    f7 varchar(64) DEFAULT NULL COMMENT '字段7|',
    f8 varchar(64) DEFAULT NULL COMMENT '字段8|',
    f9 int DEFAULT NULL COMMENT '字段9|',
    PRIMARY KEY (f1)
) ENGINE = INNODB,
AUTO_INCREMENT = 21313,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;
-- 
-- Dumping data for table table_template
--
-- Table tabletest.table_template does not contain any data (it is empty)
-- 
-- Dumping data for table testtable
--
-- Table tabletest.testtable does not contain any data (it is empty)
-- 
-- Dumping data for table table_template_share
--
-- Table tabletest.table_template_share does not contain any data (it is empty)
-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */
;
-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */
;