// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: pkg/table/registry/test/enum.proto

package rt

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "github.com/hoorayui/core-framework/pkg/proto/extension"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestEnum int32

const (
	TestEnum_TE_1 TestEnum = 0
	TestEnum_TE_2 TestEnum = 1
)

// Enum value maps for TestEnum.
var (
	TestEnum_name = map[int32]string{
		0: "TE_1",
		1: "TE_2",
	}
	TestEnum_value = map[string]int32{
		"TE_1": 0,
		"TE_2": 1,
	}
)

func (x TestEnum) Enum() *TestEnum {
	p := new(TestEnum)
	*p = x
	return p
}

func (x TestEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TestEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_table_registry_test_enum_proto_enumTypes[0].Descriptor()
}

func (TestEnum) Type() protoreflect.EnumType {
	return &file_pkg_table_registry_test_enum_proto_enumTypes[0]
}

func (x TestEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TestEnum.Descriptor instead.
func (TestEnum) EnumDescriptor() ([]byte, []int) {
	return file_pkg_table_registry_test_enum_proto_rawDescGZIP(), []int{0}
}

var File_pkg_table_registry_test_enum_proto protoreflect.FileDescriptor

var file_pkg_table_registry_test_enum_proto_rawDesc = []byte{
	0x0a, 0x22, 0x70, 0x6b, 0x67, 0x2f, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x2f, 0x72, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x72, 0x79, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x72, 0x74, 0x1a, 0x1e, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x2f, 0x65, 0x6e,
	0x75, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a, 0x38, 0x0a, 0x08, 0x54, 0x65, 0x73, 0x74,
	0x45, 0x6e, 0x75, 0x6d, 0x12, 0x15, 0x0a, 0x04, 0x54, 0x45, 0x5f, 0x31, 0x10, 0x00, 0x1a, 0x0b,
	0x82, 0xd8, 0x01, 0x07, 0xe6, 0xb5, 0x8b, 0xe8, 0xaf, 0x95, 0x31, 0x12, 0x15, 0x0a, 0x04, 0x54,
	0x45, 0x5f, 0x32, 0x10, 0x01, 0x1a, 0x0b, 0x82, 0xd8, 0x01, 0x07, 0xe6, 0xb5, 0x8b, 0xe8, 0xaf,
	0x95, 0x32, 0x42, 0x3d, 0x5a, 0x3b, 0x6a, 0x69, 0x68, 0x75, 0x6c, 0x61, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x79, 0x63, 0x77, 0x6a, 0x63, 0x6b, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x6c, 0x2d, 0x62,
	0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x74, 0x61, 0x62, 0x6c, 0x65,
	0x2f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x3b, 0x72,
	0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_table_registry_test_enum_proto_rawDescOnce sync.Once
	file_pkg_table_registry_test_enum_proto_rawDescData = file_pkg_table_registry_test_enum_proto_rawDesc
)

func file_pkg_table_registry_test_enum_proto_rawDescGZIP() []byte {
	file_pkg_table_registry_test_enum_proto_rawDescOnce.Do(func() {
		file_pkg_table_registry_test_enum_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_table_registry_test_enum_proto_rawDescData)
	})
	return file_pkg_table_registry_test_enum_proto_rawDescData
}

var file_pkg_table_registry_test_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_table_registry_test_enum_proto_goTypes = []interface{}{
	(TestEnum)(0), // 0: rt.TestEnum
}
var file_pkg_table_registry_test_enum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_table_registry_test_enum_proto_init() }
func file_pkg_table_registry_test_enum_proto_init() {
	if File_pkg_table_registry_test_enum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_table_registry_test_enum_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_table_registry_test_enum_proto_goTypes,
		DependencyIndexes: file_pkg_table_registry_test_enum_proto_depIdxs,
		EnumInfos:         file_pkg_table_registry_test_enum_proto_enumTypes,
	}.Build()
	File_pkg_table_registry_test_enum_proto = out.File
	file_pkg_table_registry_test_enum_proto_rawDesc = nil
	file_pkg_table_registry_test_enum_proto_goTypes = nil
	file_pkg_table_registry_test_enum_proto_depIdxs = nil
}
